export const mainLocators = {
  navbarBrand: `xpath=//a[normalize-space()='OK-Notes']`,
  userAvatar: 'xpath=//div[@class="user-avatar mr-2"]',
  userName: 'xpath=//div[@class="text-uppercase"]',
  basketIcon: 'xpath=//i[@class="basket_icon fa fa-shopping-basket mr-2"]',
  basketName: `xpath=(//a[contains(text(),'Корзина')])[1]`,
  basketCount: 'xpath=//span[@class="basket-count-items badge badge-primary"]',
  searchField: 'xpath=//input[@id="filterSearch"]',
  searchFieldButton: 'xpath=//button[@data-filter-action="search"]',
  typeField: 'xpath=//input[@placeholder="Тип"]',
  brandField: 'xpath=//input[@placeholder="Бренд"]',
  priceTable: 'xpath=//span[contains(text(),"Цена")]',
  fromPriceField: 'xpath=//input[@name="price-from"]',
  toPriceField: 'xpath=//input[@name="price-to"]',
  priceSearchButton: 'xpath=//button[@data-filter-action="price"]//i[@class="fa fa-search"]',
  discountCheckbox: 'xpath=//input[@id="gridCheck"]',
  discountCheckboxLabel: 'xpath=//label[@for="gridCheck"]',
  googlePasswordAlert: 'xpath=//div[contains(@class, "v-dialog")]//div[contains(text(), "Смените пароль")]',
  googlePasswordAlertCloseButton: 'xpath=//button[contains(text(), "OK")]',
  buyButtonNotepadToPoint: `xpath=//div[@class='note-list row']//div[2]//div[1]//div[2]//button[1]`,
  buyButtonGameOfThrones: `xpath=//div[3]//div[1]//div[2]//button[1]`,
  buyButtonCreativeChaos: `xpath=/html/body/div/div[1]/div/div[2]/div[1]/div/div[2]/button`,
  buyButtonCatMary: `xpath=//div[@class='note-list row']//div[4]//div[1]//div[2]//button[1]`,
  buyButtonMusicNotebook: `xpath=//div[5]//div[1]//div[2]//button[1]`,
  buyButtonBlackRed: `xpath=//div[6]//div[1]//div[2]//button[1]`,
  buyButtonGooseDeadline: `xpath=//div[7]//div[1]//div[2]//button[1]`,
  buyButtonArtist: `xpath=//div[@class='note-list row']//div[8]//div[1]//div[2]//button[1]`,
  buyButtonLittleRedRidingHood: `xpath=//div[@class='note-list row']//div[1]//div[1]//div[2]//button[1]`,
  buyButtonPlushCat: `xpath=//div[@class='note-list row']//div[2]//div[1]//div[2]//button[1]`,
  firstPageIndicator: `xpath=//a[normalize-space()='1']`,
  secondPageIndicator: `xpath=//a[normalize-space()='2']`,
  enterCountFieldCreativeChaos: `xpath=//div[@class='note-list row']//div[1]//div[1]//div[2]//div[3]//input[1]`,
}
